name: Build Windows Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Install Playwright browser
        shell: pwsh
        run: |
          $env:PLAYWRIGHT_BROWSERS_PATH="$PWD\ms-playwright"
          python -m playwright install chromium

      - name: Verify required files
        shell: pwsh
        run: |
          Write-Host "Checking tesseract..."

          if (!(Test-Path "tesseract")) {
            Write-Error "tesseract folder not found"
            exit 1
          }

          if (!(Test-Path "tesseract\tesseract.exe")) {
            Write-Error "tesseract.exe not found"
            exit 1
          }

          Write-Host "Tesseract OK"

          Write-Host "Checking Playwright..."

          if (!(Test-Path "ms-playwright")) {
            Write-Error "ms-playwright folder not found"
            exit 1
          }

          Write-Host "Playwright OK"

      - name: Build application
        shell: pwsh
        run: |
          python -m PyInstaller --clean --noconfirm --onedir `
            --name Parivahan `
            --add-data "tesseract;tesseract" `
            --add-data "ms-playwright;ms-playwright" `
            main.py

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path dist/Parivahan/* `
            -DestinationPath dist/Parivahan-Windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Parivahan-Windows
          path: dist/Parivahan-Windows.zip